site_name: ToroDB Stampede
theme: readthedocs
pages:
  - 'Welcome': index.md
  - 'About': about.md
  - 'Quickstart': quickstart.md
  - Installation:
    - 'Prerequisites': installation/prerequisites.md
    - 'Installation With Docker': installation/docker.md
    - 'Installation With Binaries': installation/binaries.md
    - 'Installation From Source Code': installation/source-code.md
  - Configuration:
    - 'Options or File': configuration/index.md
    - 'PostgreSQL Connectivity': configuration/postgresql-connectivity.md
    - 'MongoDB Connectivity': configuration/mongodb-connectivity.md
    - 'Replication Exclusion': configuration/replication-exclusion.md
    - 'Options Reference': configuration/options-reference.md
    - 'PostgreSQL Configuration Tips': configuration/postgresql-configuration-tips.md
    - 'JVM Configuration Tips': configuration/jvm-configuration-tips.md
  - 'The Relational Schema': relational-schema.md
  - 'FAQ': faq.md
  - 'Glossary': glossary.md
extra_css:
  - css/8kdata.css
markdown_extensions:
  - admonition:
